### ISSUE TITLE
RCP don't start commissioner when in Child state

### ISSUE THREAD

**Issue by bhumikaajain** [openthread/ot-br-posix#1394]
I have configured OpenThread border router on raspberry pi and attached the flashed RCP device to the Border Router platform via USB. My

Now my set-up is running fine and all other open thread nodes configured in the network are sending data to the border router, but sometimes RCP goes in child state, and when it is in child state, I cannot get the commissioner started via RCP.
Is there any way to stop RCP from going into the child state?

**Comment by jwhui** [comment]
Thread does not provide a mechanism to keep a device in the router role. Thread requires all devices to attach to an existing network as a child first before upgrading to a router.

The commissioner should be able to start on a child device - there are no restrictions to having a commissioner on a child.

Your border router could be entering the child state because it is losing connectivity with the Thread network. Have you reviewed the `otbr-agent` logs to see why the border router is entering the child role?

**Comment by jwhui** [comment]
Closing stale issue.
