### ISSUE TITLE
Multicast COAP messages from OTBR to end devices

### ISSUE THREAD

**Issue by bilalmalik76** [openthread/ot-br-posix#1788]
I am trying to use the multicast address ff03::1 to send multicast COAP messages from OTBR to the end device. But multicast messages are not getting delivered to end devices. Although I am able to send unicast messages from OTBR to end devices over COAP and also when I send a multicast message with ff03::1 from any end device, they are getting delivered to OTRB. 

Can anyone tell me what are the issues? I am using Openthread version 1.2 on both OTBR and end devices.

**Comment by jwhui** [comment]
Can you provide more detail on your setup so that others can reproduce the issue?

When sending multicast messages on Linux-based devices, it is necessary to specify the:
1. Network interface
2. Hop limit

Not specifying these values often leads to the multicast message not being delivered as expected.

**Comment by bilalmalik76** [comment]
on otbr I am using COAP command with ot-ctl to send multicast messages to end devices. For example:

ot-clt coap start 
ot-ctl coap resource light 
ot-ctl coap put ff03::1 light non-con 1

I am sending these commands from otbr. but not getting message on end devices.

**Comment by bilalmalik76** [comment]
@jwhui can you please look into this?

**Comment by jwhui** [comment]
On OTBR, the Thread network interface is presented as a standard IPv6 network interface. As a result, you should be using a CoAP library that binds directly to the network interface.

In the context of OTBR, OpenThread's built-in CoAP library (what's used when using OT CLI) is really meant for maintaining the Thread network topology itself. However, in the context of a Thread end device, the built-in CoAP library can also be used for other applications since there is only one IP network stack.
