### ISSUE TITLE
Is there any configurable option for changing the OTBR web port in docker run command 

### ISSUE THREAD

**Issue by navaneethreddy96** [openthread/ot-br-posix#1916]
**Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is.

**Describe the solution you'd like** A clear and concise description of what you want to happen.

**Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.

**Additional context** Add any other context or screenshots about the feature request here.

**Comment by navaneethreddy96** [comment]
As of now we are using the below way for running the docker run command and changing the OTBR Web port
# docker run -d --name "otbr" --network=host --sysctl "net.ipv6.conf.all.disable
_ipv6=0 net.ipv4.conf.all.forwarding=1 net.ipv6.conf.all.forwarding=1" -p 8081:8
0 -it --volume /dev/ttyACM0:/dev/ttyACM0 --privileged -e BACKBONE_INTERFACE=br1
latest-300mb-image:matter-test --radio-url spinel+hdlc+uart:///dev/ttyACM0?uart-
baudrate=460800
WARNING: Published ports are discarded when using host network mode
b4a10e6cad5991f7e9c3bc45df8e4a75b38e483f65ae6c3280b3b208ea1437c6
# ps | grep otbr
19520 root     10320 S    /usr/sbin/otbr-agent -I wpan0 -B br1 -d7 spinel+hdlc
19578 root      5632 S    /usr/sbin/otbr-web -I wpan0 -d7 -p 80
19841 root      1492 S    grep otbr
# docker exec -ti otbr sh -c "cat /etc/default/otbr-web"
OTBR_WEB_OPTS="-I wpan0 -d7 -p 80"
# docker exec -ti otbr sh -c "cat /etc/default/otbr-web"
OTBR_WEB_OPTS="-I wpan0 -d7 -p 80"
# docker exec -ti otbr sh -c "sed -i 's/-I wpan0 -d7 -p 80/-p 8082/g' /etc/defau
lt/otbr-web"
# docker exec -ti otbr sh -c "cat /etc/default/otbr-web"
OTBR_WEB_OPTS="-p 8082"
# docker exec -ti otbr sh -c "sed -i 's/-p 8082/-p 8083/g' /etc/default/otbr-web
"
# docker exec -ti otbr sh -c "cat /etc/default/otbr-web"
OTBR_WEB_OPTS="-p 8083"

Above is the manual way.  .... I am using to changing the default port from 80 to 8083 in /etc/default/otbr-web.

Is there any configurable option that i can use directly in docker run command ?

**Comment by tim-vk** [comment]
Could you properly format the issue? 

Additionally: Why are you running in host mode? (i'll be honest, I haven't gotten the image to work at all, but according to the documentation it shouldn't be neccesary). As far as I can find the current ports are hard-coded: (see: `#define OT_HTTP_PORT 80` in `src/web/main.cpp`)

When running in bridged mode you just forward the port you want to port 80. So:  `-p [your desired port]:80`.

**Comment by scyto** [comment]
> When running in bridged mode you just forward the port you want to port 80. So: `-p [your desired port]:80`.

I finally have all this working, the issue is the mDNS seems to need to be working fully, i found using a macvaln fixed my issues (host did not)  of course this means if something else needs to run on 80 then  one needs to move the port.

I can see how to do this modifying the entrypoint script to add an option.  tbh whoever wrote this was 'too clever' far easier to rely on docker vars to pass changes to the entry script vs over engineering the script as is); i might take a stab at adding an extra parsing item in the script to change -p - seems simple enough even for a non-programmer like me.

Biggest issue is figuring out to form the network when the container image is refreshed - i am unclear where the form instructions are stored (maybe not store at all) - so if it can't be store as state I assume i also need to modify the script to allow me to pass in otbr agent parameter to reform the network at start?  or as part of the entrypoint script add otbe-cli commands?

**Comment by jwhui** [comment]
> Biggest issue is figuring out to form the network automatically when the container image is refreshed - i am unclear where the form instructions are stored (maybe not stored at all?)

By default, OTBR stores non-volatile data at:
https://github.com/openthread/ot-br-posix/blob/5b1a92a0df5f4ef2f1fe35ddad740d4e8743a7b2/third_party/openthread/CMakeLists.txt#L97

**Comment by jwhui** [comment]
Closing stale issue.
