### ISSUE TITLE
[srp] OTBR does not republish the sub-device information after the router restarts

### ISSUE THREAD

**Issue by song7788** [openthread/ot-br-posix#1994]
hello, developer
    I built OTBR using Raspberry PI 4 and added the Matter device using the ChipTool-based mobile APP. Everything worked fine.I had a problem in one scene:
    1. The sub-device and router work normally, restart the Raspberry PI, and after the Raspberry PI starts and runs OTBR normally, the APP can still receive data from the sub-device normally,and everything seems to be normal
    2. The sub-device and Raspberry PI worked normally, and the router was restarted. After the router worked normally, the APP could not receive the data of the sub-device normally, and I found that OTBR did not publish the SRP information of the sub-device。
    How can I solve this problem? Or what information do you need me to provide?Or can you give me some advice?

**Comment by wgtdkp** [comment]
What is a "sub-device" specifically?

**Comment by song7788** [comment]
> What is a "sub-device" specifically?
> 
> Could you also illustrate the topology of your setup?

sub-device is Matter Over Thread device

**Comment by song7788** [comment]
I'm sorry,  something wrong with the description. my problem is that if the router restarts, OTBR does not publish SRP information for the end device, but it can search for OTBR's own mdns broadcast information on the LAN

**Comment by jwhui** [comment]
By design, the SRP Server does not store service information in non-volatile storage. As a result, after the SRP Server resets, SRP Clients are responsible for registering their services again.

The SRP Server publishes the UDP port in Thread Network Data. On reboot, the SRP Server selects a different UDP port.

https://github.com/openthread/openthread/blob/c6bece0729f0c962766ccbf01d2178e984c9f8d4/src/core/net/srp_server.cpp#L556-L576

The SRP Client should detect the change in UDP port and register its services again.

https://github.com/openthread/openthread/blob/c6bece0729f0c962766ccbf01d2178e984c9f8d4/src/core/net/srp_client.cpp#L2020

**Comment by song7788** [comment]
> By design, the SRP Server does not store service information in non-volatile storage. As a result, after the SRP Server resets, SRP Clients are responsible for registering their services again.
> 
> The SRP Server publishes the UDP port in Thread Network Data. On reboot, the SRP Server selects a different UDP port.
> 
> https://github.com/openthread/openthread/blob/c6bece0729f0c962766ccbf01d2178e984c9f8d4/src/core/net/srp_server.cpp#L556-L576
> 
> The SRP Client should detect the change in UDP port and register its services again.
> 
> https://github.com/openthread/openthread/blob/c6bece0729f0c962766ccbf01d2178e984c9f8d4/src/core/net/srp_client.cpp#L2020

thanks,I updated the openthread code to fix the problem, thanks again
