### ISSUE TITLE
[Question] How to set OTBR_RADIO_URL ?

### ISSUE THREAD

**Issue by OlivierGre** [openthread/ot-br-posix#2319]
Until now, we were editing src/agent/otbr-agent.default.in to indicate which device to use (we used ///dev//ttyUSB0 in replacement of ///dev//ttyACM0). The content of this file is copied to /etc/default/otbr-agent.

I can see that the file now contains "OTBR_RADIO_URL". Can you please tell me how to overwrite it? Shall I set an envionment variable on the Raspberry Pi?

Thanks

**Comment by Irving-cl** [comment]
Hi @OlivierGre,

`OTBR_RADIO_URL` is defined in the root [CMakeLists.txt](https://github.com/openthread/ot-br-posix/blob/main/CMakeLists.txt#L43). Since in the `set(OTBR_RADIO_URL ...)` there is no `FORCE`, so you can still overwrite it by: `OTBR_OPTIONS="-DOTBR_RADIO_URL=spinel+hdlc+uart:///dev/ttyUSB0" ./script/setup`. Or you can simply update the CMakeLists.txt.

One tip that may be helpful: You can search the options you're interested by running grep command under ot-br-posix repo `grep -rn --exclude-dir=build [key word] ./`

**Comment by zhanglongxia** [comment]
You can refer to this [PR46](https://github.com/openthread/ot-reference-release/pull/46) to set the `OTBR_RADIO_URL`.

**Comment by OlivierGre** [comment]
Thanks to both of you
