### ISSUE TITLE
otbr-agent received signal SIGSEGV, Segmentation fault. (ProcessFrameQueue)

### ISSUE THREAD

**Issue by jinpeng1989** [openthread/ot-br-posix#2476]
Describe the bug:
The otbr-agent process crashed, and GDB debugging found that the error was near the ProcessFrameQueue function.
The ot-br-posix code used is: https://github.com/SiliconLabs/simplicity_sdk/tree/sisdk-2024.6/util/third_party/ot-br-posix
![1244e6f84f76f120bddd1793bbe42e7](https://github.com/user-attachments/assets/339067eb-3c30-4185-813a-869fd036fc93)

**Comment by jinpeng1989** [comment]
Crash here, please see log.
[SyslogCatchAll-2024-08-28-1-and-2.zip](https://github.com/user-attachments/files/16888334/SyslogCatchAll-2024-08-28-1-and-2.zip)
![image](https://github.com/user-attachments/assets/bcd5fd0a-54b2-4a49-a575-f8e8994c758d)

**Comment by abtink** [comment]
@Irving-cl  can you help take a look and provide your toughts on this?

It seems to be this assert in `void SpinelDriver::ProcessFrameQueue(void)`.
```c++
    assert(mSavedFrameHandler != nullptr && mFrameHandlerContext != nullptr);
```

I see we have ` SetFrameHandler()` to set the handlers and it should be set from `RadioSpinel::Init()`? Not sure it may be unset while `Process()` is called? 

We can consider relaxing this to checking it with `OT_EXPECT()` instead of assert?  What do you think?

(a related topic is if we should allow `mFrameHandlerContext` to be possibly `nullptr`, since a callback with `null` context is technically valid).
