### ISSUE TITLE
Commissioner not started via otbr-web GUI.

### ISSUE THREAD

**Issue by tarunsmalviya** [openthread/ot-br-posix#287]
**Describe the bug**
I started commissioner via web GUI. The popup shows commission operation is success, but when I checked commissioner state with command `sudo wpanctl get Commissioner:State`, the state is still disabled. Also the scan result shows that network is unjoinable.

<img width="271" alt="Screenshot 2019-05-07 at 11 54 39 AM" src="https://user-images.githubusercontent.com/9993036/57276604-bd63a780-70bf-11e9-8e2d-06f6b6680776.png">

![Screenshot 2019-05-07 at 12 00 57 PM](https://user-images.githubusercontent.com/9993036/57276681-f1d76380-70bf-11e9-8c6e-4661342fcaf6.png)

**Comment by gjc13** [comment]
The Commissioner:State property shows whether the on-mesh commissioner is started which is not used by the web gui. 
At the end of commission process, the commissioner will retire so you will find the network to become unjoinable again.
Can your device get the network parameter via the commission process?

**Comment by jwhui** [comment]
@tarunsmalviya, can you provide any updates?

**Comment by tarunsmalviya** [comment]
@jwhui Apologies for delay in response. 
According to me, whenever commissioner is started for a time period provided, the value of  **Commissioner:State** is active. I am not getting your point.
Can you explain the commission feature in Web GUI?

**Comment by bukepo** [comment]
@gjc13 could you please help on this?

**Comment by gjc13** [comment]
Let's say you run
```
curl --header "Content-Type: application/json" --request POST --data '{"pskd":"ABCDEF", "passphrase":"123456"}' http://127.0.0.1:8080/commission
```
When the web server get the POST request, it constructs a commissioner object and start the commissioning process and the network becomes joinable. Since this is not an on-mesh commissioner, the Commissioner:State will not change.
Then you will run `joiner start ABCDEF` on a device and the joiner gets the proper network parameters. On the server side, upon the success of the join process, the commissioner will be destructed and the server will send the reply to http POST. Then the network becomes not joinable again.

**Comment by jwhui** [comment]
Closing stale issue.
