### ISSUE TITLE
Could not setup Rpi3B as otbr

### ISSUE THREAD

**Issue by hao-gao** [openthread/ot-br-posix#467]
Could not setup Rpi3B as otbr at ./script/bootstrap, see in https://github.com/openthread/ot-br-posix/commit/0a9ed6ad411314730545ed550873105251c7923d

**Comment by bukepo** [comment]
It seems there are some network errors. Could you try again or configure your pip to use a different mirror?

**Comment by hao-gao** [comment]
could you please also add `set -x` in that after_bootstrap.sh, so users like me are able to find out what's going on there, without browsing the source? Thanks

**Comment by simonlingoogle** [comment]
I have had this same issue many times when setting up otbr (in China).
With some investigation, I realized that this might be caused by the GFW. More specifically, because `pip` is trying to download the package from an IPv6 destination address, but failed. 
Each time `pip` is invoked, it will either resolve the destination domain as IPv6 address (larger chance) or IPv4 address (smaller chance). It will succeed when you are lucky enough to have `pip` using IPv4 address. 

**A simple solution is retrying for tens of times, which will succeed eventually.**
