### ISSUE TITLE
router table cli command with not complete answer

### ISSUE THREAD

**Issue by nicho2** [openthread/ot-br-posix#611]
i do this command:

sudo ot-ctl router table

and the response is not complete:
| ID | RLOC16 | Next Hop | Path Cost | LQ In | LQ Out | Age | Extended MAC     |
+----+--------+----------+-----------+-------+--------+-----+------------------+
|  3 | 0x0c00 |       63 |         0 |     0 |      0 | 125 | 0000000000000000 |
| 17 | 0x4400 |       63 |         0 |     0 |      0 | 125 | 0000000000000000 |
| 21 | 0x5400 |       63 |         0 |     0 |      0 | 125 | 0000000000000000 |
| 25 | 0x6400 |       26 |        12 |     0 |      0 | 153 | 0000000000000000 |
| 26 | 0x6800 |       56 |         1 |     3 |      3 |  89 | 6286d2e318f27384 |
| 27 | 0x6c00 |       63 |         0 |     0 |      0 | 125 | 0000000000000000 |
| 31 | 0x7c00 |       63 |         0 |     0 |      0 |   0 | da72ea2354e42713 |
| 34 | 0x8800 |       56 |         1 |     2 |      2 |   6 | e62ed34a82fee150 |
| 55 | 0xdc00 |       56 |         2 |     1 |      1 |   6 | 2e3834f973e8fb42 |
| 56 | 0xe000 |       26 |         1 |     3 |      3 |  12 | b6f45e429ad94fd9 |
| 59 | 0xec00 |       26 |         1 |

i must do CTRL + C to exit from this situation

**Comment by jwhui** [comment]
@nicho2 , thanks for raising this issue. Can you provide more information on your setup?

1. Git commit id
2. IEEE 802.15.4 hardware platform
3. Build steps

**Comment by vijayrao1988** [comment]
The fix for this is to update the source-code. In the file `/ot-br-posix/third_party/openthread/repo/src/cli/cli_config.h`, change the size of the serial buffer, by modifying this line `#define OPENTHREAD_CONFIG_CLI_UART_TX_BUFFER_SIZE 1024`, from a buffer of 1024 to a buffer of an appropriate size for your router table.

For example for a buffer size of 10240, which should support about 100 nodes on the network.
`#define OPENTHREAD_CONFIG_CLI_UART_TX_BUFFER_SIZE 10240`

After making this modification, run the following commands in the base folder of ot-br-posix:
`> ./script/bootstrap`
`> ./script/setup`

If you reboot, ot-ctl should now pick up the modifications and the issue with router table should get solved.

**Comment by jwhui** [comment]
Closing stale issue.
