### ISSUE TITLE
udp message from ipv4 to ipv6

### ISSUE THREAD

**Issue by hansdeweerd** [openthread/ot-br-posix#769]
is it possible to send a udp message to a node in a thread network?

i can send a udp message from a node on my computer, this computer is connect to a ipv4 only network. this is done by using tayga. but how can i responde to this?

**Comment by jwhui** [comment]
OTBR implements NAT64 using TAYGA. As is typical with stateful NAT, communications must be initiated by Thread devices so that the NAT can setup the network translation mapping. An IPv4 host responding to a UDP/IPv4 message initiated by a Thread device should be able to respond to the packet's IPv4 source address and UDP source port.

**Comment by hansdeweerd** [comment]
ok, thanks. but the source address from the ping and the upd message are from raspberry pi. 

what am I doing wrong then? Tayga gives the node in the thread network an ipv4 address from the dynamic pool. but the source address is still from the raspberry pi.

**Comment by jwhui** [comment]
> ok, thanks. but the source address from the ping and the upd message are from raspberry pi.
> 
> what am I doing wrong then? Tayga gives the node in the thread network an ipv4 address from the dynamic pool. but the source address is still from the raspberry pi.

That is how stateful NAT is typically configured. The NAT uses the IPv4 address assigned to its external interface as the external IPv4 address and uses the external UDP port to map to an internal IPv6 address an UDP port.

**Comment by jwhui** [comment]
Closing stale issue.
